import kilik from "./../assets/characters/thumb/kilik.png";
import azwel from "./../assets/characters/thumb/azwel.png";
import astaroth from "./../assets/characters/thumb/astaroth.png";
import cervantes from "./../assets/characters/thumb/cervantes.png";
import geralt from "./../assets/characters/thumb/geralt.png";
import groh from "./../assets/characters/thumb/groh.png";
import ivy from "./../assets/characters/thumb/ivy.png";
import maxi from "./../assets/characters/thumb/maxi.png";
import mitsurugi from "./../assets/characters/thumb/mitsurugi.png";
import nightmare from "./../assets/characters/thumb/nightmare.png";
import siegfried from "./../assets/characters/thumb/siegfried.png";
import sophitia from "./../assets/characters/thumb/sophitia.png";
import taki from "./../assets/characters/thumb/taki.png";
import talim from "./../assets/characters/thumb/talim.png";
import tira from "./../assets/characters/thumb/tira.png";
import voldo from "./../assets/characters/thumb/voldo.png";
import xianghua from "./../assets/characters/thumb/xianghua.png";
import yoshimitsu from "./../assets/characters/thumb/yoshimitsu.png";
import zasalamel from "./../assets/characters/thumb/zasalamel.png";
import seongMiNa from "./../assets/characters/thumb/seong-mi-na.png";

export default n => {
  const name = n.toLowerCase();

  if (name === "kilik") return kilik;
  if (name === "azwel") return azwel;
  if (name === "astaroth") return astaroth;
  if (name === "cervantes") return cervantes;
  if (name === "geralt") return geralt;
  if (name === "groh") return groh;
  if (name === "ivy") return ivy;
  if (name === "maxi") return maxi;
  if (name === "mitsurugi") return mitsurugi;
  if (name === "nightmare") return nightmare;
  if (name === "siegfried") return siegfried;
  if (name === "sophitia") return sophitia;
  if (name === "taki") return taki;
  if (name === "talim") return talim;
  if (name === "tira") return tira;
  if (name === "voldo") return voldo;
  if (name === "xianghua") return xianghua;
  if (name === "yoshimitsu") return yoshimitsu;
  if (name === "zasalamel") return zasalamel;
  if (name === "seong-mi-na") return seongMiNa;
};
